export const FETCH_BREEDS_BEGIN = 'FETCH_BREEDS_BEGIN'
export const FETCH_BREEDS_SUCCESS = 'FETCH_BREEDS_SUCCESS'
export const FETCH_BREEDS_ERROR = 'FETCH_BREEDS_ERROR'

export const FETCH_TYPES_BEGIN = 'FETCH_TYPES_BEGIN'
export const FETCH_TYPES_SUCCESS = 'FETCH_TYPES_SUCCESS'
export const FETCH_TYPES_ERROR = 'FETCH_TYPES_ERROR'

export const SET_SELECTED_TYPE = 'SET_SELECTED_TYPE'

export const FETCH_ANIMALS_BEGIN = 'FETCH_ANIMALS_BEGIN'
export const FETCH_ANIMALS_SUCCESS = 'FETCH_ANIMALS_SUCCESS'
export const FETCH_ANIMALS_ERROR = 'FETCH_ANIMALS_ERROR'

export const SET_VALUE = 'SET_VALUE'
export const RESET_VALUES = 'RESET_VALUES'