export const FETCH_BREEDS_BEGIN = 'FETCH_BREEDS_BEGIN'
export const FETCH_BREEDS_SUCCESS = 'FETCH_BREEDS_SUCCESS'
export const FETCH_BREEDS_ERROR = 'FETCH_BREEDS_ERROR'

export const FETCH_TYPE_BEGIN = 'FETCH_TYPE_BEGIN'
export const FETCH_TYPE_SUCCESS = 'FETCH_TYPE_SUCCESS'
export const FETCH_TYPE_ERROR = 'FETCH_TYPE_ERROR'

export const FETCH_ANIMALS_BEGIN = 'FETCH_ANIMALS_BEGIN'
export const FETCH_ANIMALS_SUCCESS = 'FETCH_ANIMALS_SUCCESS'
export const FETCH_ANIMALS_ERROR = 'FETCH_ANIMALS_ERROR'